# ansible_env_ready.yml
---
- name: Setup Base System and Dependencies (Multi-OS)
  hosts: localhost
  gather_facts: yes
  become: yes

  vars:
    # 공통 변수
    sqlite_download_url: "https://raw.githubusercontent.com/negun2/soldesk/main/files/sqlite-snapshot-202505171106.tar.gz"
    sqlite_downloaded_filename: "sqlite-snapshot-202505171106.tar.gz"
    sqlite_download_dest_dir: "/tmp/sqlite_downloaded"
    sqlite_install_prefix: "/usr/local"

    # OS별 변수 파일 다운로드 URL 및 경로
    os_vars_base_url: "https://raw.githubusercontent.com/negun2/soldesk/refs/heads/main/vars"
    downloaded_vars_dir: "{{ ansible_user_dir | default('/home/vagrant') }}/downloaded_vars"



    downloaded_vars_dir: "{{ ansible_user_dir | default('/home/vagrant') }}/downloaded_vars" # 이 경로는 /root/downloaded_vars 가 됨

  tasks:
    - name: Create directory for downloaded OS vars files
      file:
        path: "{{ downloaded_vars_dir }}"
        state: directory
        mode: '0755'

    - name: Download OS-specific var files from GitHub
      get_url:
        url: "{{ os_vars_base_url }}/{{ item }}"
        dest: "{{ downloaded_vars_dir }}/{{ item }}"
        mode: '0755'
      loop:
        - "RedHat.yml"
        - "Debian.yml"
        # 추가적인 OS별 _django.yml 파일 등을 사용한다면 여기에 추가
      ignore_errors: yes # 특정 파일이 없을 경우 대비

    - name: Display content of downloaded Debian.yml for debugging
      command: "cat {{ downloaded_vars_dir }}/Debian.yml"
      register: debian_vars_content
      when: ansible_os_family == "Debian"
      changed_when: false # 상태 변경 안 함
      ignore_errors: yes # 파일이 없을 경우 대비

    - name: Show downloaded Debian.yml content
      debug:
        var: debian_vars_content.stdout_lines
      when: ansible_os_family == "Debian" and debian_vars_content.stdout is defined

    - name: Include OS-specific variables from downloaded files
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "{{ downloaded_vars_dir }}/{{ ansible_os_family }}.yml"
            # - "{{ downloaded_vars_dir }}/default.yml" # 공통 기본값 파일
          skip: true # 파일이 없어도 오류 발생 안 함

    # --- RedHat 계열 패키지 설치 ---
    - name: Install base packages (RedHat family)
      yum:
        name:
          - epel-release
          - python3
          - python3-pip
          - gcc
          - "{{ python_dev_package_name }}"
          - "{{ apache_package_name }}"
          - "{{ apache_dev_package_name }}"
          - "{{ mod_wsgi_package_name_system }}" # 시스템 Apache용 mod_wsgi
          - "{{ python_virtualenv_package_name }}"
          - wget
          - "{{ readline_dev_package_name }}"
          - "{{ zlib_dev_package_name }}"
          - "{{ libffi_dev_package_name }}"
          - "{{ libssl_dev_package_name }}"
          - "{{ policycoreutils_package_name | default(omit) }}"
        state: present
      when: ansible_os_family == "RedHat"

    # --- Debian 계열 패키지 설치 ---
    - name: Install base packages (Debian family)
      apt:
        name:
          - python3
          - python3-pip
          - gcc
          - "{{ python_dev_package_name }}"
          - "{{ apache_package_name }}"
          - "{{ apache_dev_package_name }}"
          - "{{ mod_wsgi_package_name_system }}" # 시스템 Apache용 mod_wsgi
          - "{{ python_virtualenv_package_name }}"
          - wget
          - "{{ readline_dev_package_name }}"
          - "{{ zlib_dev_package_name }}"
          - "{{ libffi_dev_package_name }}"
          - "{{ libssl_dev_package_name }}"
          - "{{ policycoreutils_package_name | default(omit) }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install 'Development Tools' group (RedHat family only)
      yum:
        name: "@Development Tools"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install 'build-essential' (Debian family for development tools)
      apt:
        name: build-essential
        state: present
      when: ansible_os_family == "Debian"

    - name: Create download and extraction directory for SQLite
      file:
        path: "{{ sqlite_download_dest_dir }}"
        state: directory
        mode: '0755'

    - name: Download SQLite source from GitHub
      get_url:
        url: "{{ sqlite_download_url }}"
        dest: "{{ sqlite_download_dest_dir }}/{{ sqlite_downloaded_filename }}"
        mode: '0644'
      register: sqlite_download_status
      until: sqlite_download_status is succeeded
      retries: 3
      delay: 5

    - name: Unarchive SQLite source
      unarchive:
        src: "{{ sqlite_download_dest_dir }}/{{ sqlite_downloaded_filename }}"
        dest: "{{ sqlite_download_dest_dir }}"
        remote_src: yes
      register: sqlite_unarchive_result

    - name: Configure SQLite
      command: "./configure --prefix={{ sqlite_install_prefix }} --enable-shared --enable-fts5"
      args:
        chdir: "{{ sqlite_unarchive_result.dest }}/{{ sqlite_downloaded_filename | basename | regex_replace('.tar.gz$', '') }}"
      changed_when: false

    - name: Compile SQLite
      command: "make -j{{ ansible_processor_vcpus | default(1) }}"
      args:
        chdir: "{{ sqlite_unarchive_result.dest }}/{{ sqlite_downloaded_filename | basename | regex_replace('.tar.gz$', '') }}"
      changed_when: false

    - name: Install SQLite
      command: "make install"
      args:
        chdir: "{{ sqlite_unarchive_result.dest }}/{{ sqlite_downloaded_filename | basename | regex_replace('.tar.gz$', '') }}"

    - name: Configure dynamic linker run-time bindings for SQLite
      copy:
        content: "{{ sqlite_install_prefix }}/lib"
        dest: /etc/ld.so.conf.d/sqlite3-custom.conf
        mode: '0644'
      notify: Run ldconfig

    - name: Clean up SQLite download and extraction directory
      file:
        path: "{{ sqlite_download_dest_dir }}"
        state: absent

  handlers:
    - name: Run ldconfig
      command: ldconfig

# --- 다음 플레이 ---
- name: Setup Django Web Environment (Multi-OS)
  hosts: localhost
  become: yes
  gather_facts: yes

  vars:
    # 공통 변수
    target_user_home: "{{ ansible_user_dir | default('/home/vagrant') }}"
    target_user: "{{ ansible_user_id | default('vagrant') }}"
    project_root_dir: "{{ target_user_home }}/onpremweb"
    venv_dir: "{{ project_root_dir }}/venv"
    django_project_name: "onpremweb"
    django_project_config_name: "onprem_project_config"
    django_version: "3.2.25"

    os_vars_base_url: "https://raw.githubusercontent.com/negun2/soldesk/main/vars"
    downloaded_vars_dir: "{{ ansible_user_dir | default('/home/vagrant') }}/downloaded_vars"

    apache_conf_template_download_url: "https://raw.githubusercontent.com/negun2/soldesk/main/templates/django_onpremweb.conf.j2"
    apache_conf_template_downloaded_filename: "django_onpremweb.conf.j2"
    ansible_playbook_dir: "{{ target_user_home }}" # 플레이북이 다운로드된 경로
    vm_templates_dir: "{{ ansible_playbook_dir }}/templates_downloaded"

    # OS별 변수 기본값 (로드 실패 대비)
    apache_user: ""
    apache_group: ""
    apache_conf_dir: ""
    apache_sites_enabled_dir: ""
    apache_service_name: ""
    mod_wsgi_load_file_content_django: "" # Django 플레이용 mod_wsgi 로드 내용 (OS별 vars_django에서 정의)

  tasks:
    - name: Ensure downloaded_vars_dir exists (for idempotency)
      file:
        path: "{{ downloaded_vars_dir }}"
        state: directory
        mode: '0755'
      changed_when: false # 이미 생성되었을 가능성이 높음

    - name: Include OS-specific variables for Django environment from downloaded files
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "{{ downloaded_vars_dir }}/{{ ansible_os_family }}_django.yml" # 예: RedHat_django.yml (만약 있다면)
            - "{{ downloaded_vars_dir }}/{{ ansible_os_family }}.yml"      # 또는 일반 OS별 파일
          skip: true

    - name: Ensure project directory exists
      file:
        path: "{{ project_root_dir }}"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Create Python virtual environment
      command: "python3 -m venv {{ venv_dir }}"
      args:
        creates: "{{ venv_dir }}/bin/activate"
      become_user: "{{ target_user }}"

    - name: Install Django and mod_wsgi in virtual environment
      pip:
        name:
          - "django=={{ django_version }}"
          - mod_wsgi # 가상환경에 mod_wsgi 설치 (Apache가 이 환경을 사용)
        virtualenv: "{{ venv_dir }}"
        virtualenv_python: python3
      become_user: "{{ target_user }}"

    - name: Ensure mod_wsgi module is loaded in Apache (RedHat family)
      copy: # RedHat에서는 mod_wsgi 로드 파일을 직접 관리할 수 있음
        content: "{{ mod_wsgi_load_file_content_django | default('LoadModule wsgi_module modules/mod_wsgi_python3.so') }}"
        dest: "/etc/httpd/conf.modules.d/10-wsgi-custom.conf" # 시스템 패키지와 다른 이름 사용
        owner: root
        group: root
        mode: '0644'
      when: ansible_os_family == "RedHat"
      notify: Restart Apache

    - name: Enable wsgi module on Debian family
      command: "a2enmod wsgi_py3" # Ubuntu/Debian은 패키지 설치 시 모듈이 준비되고, a2enmod로 활성화
      args:
        creates: "/etc/apache2/mods-enabled/wsgi_py3.load" # 또는 wsgi.load
      when: ansible_os_family == "Debian"
      notify: Restart Apache

    - name: Create Django project
      command: "{{ venv_dir }}/bin/django-admin startproject {{ django_project_config_name }} {{ project_root_dir }}"
      args:
        creates: "{{ project_root_dir }}/manage.py"
      become_user: "{{ target_user }}"

    - name: Configure Django settings
      lineinfile:
        path: "{{ project_root_dir }}/{{ django_project_config_name }}/settings.py"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.insertafter | default('^# Application definition') }}"
        create: yes
      loop:
        - { regexp: "^STATIC_URL = .*", line: "STATIC_URL = '/static/'", insertafter: "^BASE_DIR = .*" }
        - { regexp: "^STATIC_ROOT = .*", line: "STATIC_ROOT = BASE_DIR / 'staticfiles'", insertafter: "^BASE_DIR = .*" }
        - { regexp: "^MEDIA_URL = .*", line: "MEDIA_URL = '/media/'", insertafter: "^BASE_DIR = .*" }
        - { regexp: "^MEDIA_ROOT = .*", line: "MEDIA_ROOT = BASE_DIR / 'mediafiles'", insertafter: "^BASE_DIR = .*" }
        - { regexp: "^ALLOWED_HOSTS = .*", line: "ALLOWED_HOSTS = ['*']" }
        - { regexp: "^# import os", line: "import os", insertbefore: "^BASE_DIR = .*" }

    - name: Create staticfiles and mediafiles directories
      file:
        path: "{{ project_root_dir }}/{{ item }}"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'
      loop:
        - staticfiles
        - mediafiles
      become_user: "{{ target_user }}"

    - name: Collect static files
      command: "{{ venv_dir }}/bin/python {{ project_root_dir }}/manage.py collectstatic --noinput"
      become_user: "{{ target_user }}"
      args:
        chdir: "{{ project_root_dir }}"

    - name: Set permissions for project directory for Apache
      file:
        path: "{{ item }}"
        owner: "{{ target_user }}"
        group: "{{ apache_group }}" # OS별 Apache 그룹
        mode: "{{ 'g+rX' if item == project_root_dir else '0775' }}"
        recurse: "{{ 'yes' if item != project_root_dir else 'no' }}"
      loop:
        - "{{ project_root_dir }}"
        - "{{ project_root_dir }}/staticfiles"
        - "{{ project_root_dir }}/mediafiles"
        - "{{ venv_dir }}"

    - name: Allow Apache to search user's home directory
      file:
        path: "{{ target_user_home }}"
        mode: '0755' # 좀 더 명확한 권한 (소유자rwx, 그룹rx, otherrx)

    - name: Create directory for downloaded Apache template on VM
      file:
        path: "{{ vm_templates_dir }}"
        state: directory
        mode: '0755'

    - name: Download Apache config template from GitHub
      get_url:
        url: "{{ apache_conf_template_download_url }}"
        dest: "{{ vm_templates_dir }}/{{ apache_conf_template_downloaded_filename }}"
        mode: '0644'

    - name: Deploy Apache virtual host configuration for Django
      template:
        src: "{{ vm_templates_dir }}/{{ apache_conf_template_downloaded_filename }}"
        dest: "{{ apache_conf_dir }}/{{ django_project_name }}.conf" # OS별 설정 디렉토리 사용
        owner: root
        group: root
        mode: '0644'
      notify: Restart Apache

    - name: Clean up downloaded Apache template directory on VM
      file:
        path: "{{ vm_templates_dir }}"
        state: absent

    - name: Enable Apache site (Debian family only)
      command: "a2ensite {{ django_project_name }}"
      args:
        creates: "{{ apache_sites_enabled_dir }}/{{ django_project_name }}.conf" # OS별 활성화된 사이트 경로
      when: ansible_os_family == "Debian"
      notify: Restart Apache

    - name: Ensure Apache service is enabled and running
      service:
        name: "{{ apache_service_name }}" # OS별 서비스 이름 사용
        state: started
        enabled: yes

    - name: Configure SELinux for Apache (RedHat family only)
      block:
        - name: Allow httpd to access project files (SELinux)
          sefcontext:
            target: "{{ project_root_dir }}(/.*)?"
            setype: httpd_sys_content_t
            state: present
          notify: Restore SELinux context

        - name: Allow httpd to access user home directories (SELinux boolean)
          seboolean:
            name: httpd_enable_homedirs
            state: yes
            persistent: yes
      when: ansible_os_family == "RedHat"
      ignore_errors: yes # policycoreutils-python 없을 경우 대비

    - name: Ensure firewall is configured for http
      block:
        - name: Allow http on firewalld (RedHat family)
          firewalld:
            service: http
            permanent: yes
            state: enabled
          notify: Reload firewalld
          when: ansible_os_family == "RedHat"

        - name: Allow http on ufw (Debian family)
          ufw:
            rule: allow
            port: '80'
            proto: tcp
          notify: Reload ufw
          when: ansible_os_family == "Debian"
      ignore_errors: yes

  handlers:
    - name: Restart Apache
      service:
        name: "{{ apache_service_name }}"
        state: restarted

    - name: Restore SELinux context
      command: "restorecon -Rv {{ project_root_dir }}"
      when: ansible_os_family == "RedHat"

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded
      when: ansible_os_family == "RedHat"

    - name: Reload ufw
      command: ufw reload # 또는 service 모듈 사용 (ufw 서비스가 systemd로 관리된다면)
      when: ansible_os_family == "Debian"
