---
- name: Setup Base System and Dependencies (Multi-OS)
  hosts: localhost
  gather_facts: yes
  become: yes

  vars:
    sqlite_download_url: "https://raw.githubusercontent.com/negun2/soldesk/main/files/sqlite-snapshot-202505171106.tar.gz"
    sqlite_downloaded_filename: "sqlite-snapshot-202505171106.tar.gz"
    sqlite_download_dest_dir: "/tmp/sqlite_downloaded"
    sqlite_install_prefix: "/usr/local"
    os_vars_base_url: "https://raw.githubusercontent.com/negun2/soldesk/main/vars"
    downloaded_vars_dir: "/tmp/downloaded_os_vars"
    mod_wsgi_package_name_system: "mod_wsgi"  # fallback 기본값 지정

  tasks:
    - name: Create directory for downloaded OS vars files
      file:
        path: "{{ downloaded_vars_dir }}"
        state: directory
        mode: '0755'

    - name: Download OS-specific var files from GitHub
      get_url:
        url: "{{ os_vars_base_url }}/{{ item }}"
        dest: "{{ downloaded_vars_dir }}/{{ item }}"
        mode: '0644'
      loop:
        - "RedHat.yml"
        - "Debian.yml"
      ignore_errors: yes

    - name: Include OS-specific vars
      include_vars: "{{ downloaded_vars_dir }}/{{ ansible_os_family }}.yml"

    - name: Install IUS Community repository (RedHat family only)
      yum:
        name: "https://repo.ius.io/ius-release-el7.rpm"
        state: present
        disable_gpg_check: yes
      when: ansible_os_family == "RedHat"

    - name: Install base packages (RedHat)
      yum:
        name:
          - epel-release
          - python3
          - python3-pip
          - gcc
          - "{{ python_dev_package_name | default('python3-devel') }}"
          - "{{ apache_package_name | default('httpd') }}"
          - "{{ apache_dev_package_name | default('httpd-devel') }}"
          - "{{ mod_wsgi_package_name_system | default('mod_wsgi') }}"
          - "{{ python_virtualenv_package_name | default('python3-virtualenv') }}"
          - wget
          - "{{ readline_dev_package_name | default('readline-devel') }}"
          - "{{ zlib_dev_package_name | default('zlib-devel') }}"
          - "{{ libffi_dev_package_name | default('libffi-devel') }}"
          - "{{ libssl_dev_package_name | default('openssl-devel') }}"
          - "{{ policycoreutils_package_name | default('policycoreutils-python') }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install base packages (Debian)
      apt:
        name:
          - python3
          - python3-pip
          - gcc
          - "{{ python_dev_package_name | default('python3-dev') }}"
          - "{{ apache_package_name | default('apache2') }}"
          - "{{ apache_dev_package_name | default('apache2-dev') }}"
          - "{{ mod_wsgi_package_name_system | default('libapache2-mod-wsgi-py3') }}"
          - "{{ python_virtualenv_package_name | default('python3-venv') }}"
          - wget
          - "{{ readline_dev_package_name | default('libreadline-dev') }}"
          - "{{ zlib_dev_package_name | default('zlib1g-dev') }}"
          - "{{ libffi_dev_package_name | default('libffi-dev') }}"
          - "{{ libssl_dev_package_name | default('libssl-dev') }}"
          - "{{ apparmor_utils_package_name | default('apparmor-utils') }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install development tools
      block:
        - name: Install 'Development Tools' group (RedHat)
          yum:
            name: "@Development Tools"
            state: present
          when: ansible_os_family == "RedHat"

        - name: Install 'build-essential' (Debian)
          apt:
            name: build-essential
            state: present
          when: ansible_os_family == "Debian"

    - name: Download and compile SQLite
      block:
        - name: Create download directory
          file:
            path: "{{ sqlite_download_dest_dir }}"
            state: directory
            mode: '0755'

        - name: Download SQLite source
          get_url:
            url: "{{ sqlite_download_url }}"
            dest: "{{ sqlite_download_dest_dir }}/{{ sqlite_downloaded_filename }}"
            mode: '0644'
          register: sqlite_download_status
          until: sqlite_download_status is succeeded
          retries: 3
          delay: 5

        - name: Unarchive SQLite
          unarchive:
            src: "{{ sqlite_download_dest_dir }}/{{ sqlite_downloaded_filename }}"
            dest: "{{ sqlite_download_dest_dir }}"
            remote_src: yes
          register: sqlite_unarchive_result

        - name: Configure, build, and install SQLite
          command: "{{ item }}"
          args:
            chdir: "{{ sqlite_unarchive_result.dest }}/{{ sqlite_downloaded_filename | basename | regex_replace('.tar.gz$', '') }}"
          loop:
            - "./configure --prefix={{ sqlite_install_prefix }} --enable-shared --enable-fts5"
            - "make -j{{ ansible_processor_vcpus | default(1) }}"
            - "make install"

        - name: Configure dynamic linker for SQLite
          copy:
            content: "{{ sqlite_install_prefix }}/lib"
            dest: /etc/ld.so.conf.d/sqlite3-custom.conf
            mode: '0644'
          notify: Run ldconfig

        - name: Clean up SQLite source
          file:
            path: "{{ sqlite_download_dest_dir }}"
            state: absent

    - name: Ensure SELinux rules for Apache and project
      block:
        - name: Allow httpd to access project files
          sefcontext:
            target: "{{ project_root_dir }}(/.*)?"
            setype: httpd_sys_content_t
            state: present

        - name: Allow httpd to write to media directory
          sefcontext:
            target: "{{ project_root_dir }}/mediafiles(/.*)?"
            setype: httpd_sys_rw_content_t
            state: present

        - name: Allow httpd network connections
          seboolean:
            name: httpd_can_network_connect
            state: yes
            persistent: yes

        - name: Allow httpd database connections
          seboolean:
            name: httpd_can_network_connect_db
            state: yes
            persistent: yes

      when: ansible_os_family == "RedHat"

    - name: Ensure firewalld is enabled and allows HTTP
      block:
        - name: Ensure firewalld is installed and running
          service:
            name: firewalld
            state: started
            enabled: yes

        - name: Open HTTP and HTTPS ports
          firewalld:
            port: "{{ item }}"
            permanent: true
            state: enabled
            immediate: yes
          loop:
            - 80/tcp
            - 443/tcp

      when: ansible_os_family == "RedHat"

  handlers:
    - name: Run ldconfig
      command: ldconfig

# (Django Web Environment play는 기존 상태 유지)
# SELinux, firewalld 설정은 이 플레이에 포함되어 있기 때문에 별도로 추가하지 않음
