---
# provision_openvpn_client.yml
- name: Configure OpenVPN client on on-prem Vagrant VM
  hosts: localhost
  connection: local
  become: yes
  vars:
    # OpenVPN 서버 공인 IP 또는 도메인
    openvpn_server_ip: "61.72.114.125"
    # OpenVPN 서버 쪽에서 발급한 client.ovpn 파일 경로 (GitHub, S3 등)
    client_config_url: "https://example.com/path/to/client.ovpn"
    # 로컬에 저장할 경로
    client_config_dest: "/etc/openvpn/client/client.conf"

  tasks:
    - name: Install OpenVPN client
      package:
        name: openvpn
        state: present

    - name: Create client config directory
      file:
        path: "{{ client_config_dest | dirname }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Download client.ovpn
      get_url:
        url: "{{ client_config_url }}"
        dest: "{{ client_config_dest }}"
        mode: '0600'
        owner: root
        group: root

    - name: Ensure client config uses correct remote
      replace:
        path: "{{ client_config_dest }}"
        regexp: '^remote\s+.*$'
        replace: "remote {{ openvpn_server_ip }} 1194 udp"
      notify: Restart OpenVPN client

    - name: Enable and start OpenVPN client service
      systemd:
        name: openvpn-client@client
        enabled: yes
        state: started

  handlers:
    - name: Restart OpenVPN client
      systemd:
        name: openvpn-client@client
        state: restarted
